name: Python & React Application CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Set up Python and install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run Python Linter (flake8)
    - name: Lint Python with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    # Run Python Tests (inside `unittest/`)
    - name: Test Python Code
      run: |
        python -m unittest discover -s unittest -p "test_*.py"

    # Set up Node.js for JavaScript/React
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install JavaScript Dependencies
      run: |
        if [ -f package.json ]; then npm install; fi

    # Run JavaScript/React Linter (ESLint)
    - name: Lint JavaScript/React with ESLint
      run: |
        if [ -f package.json ]; then npx eslint . --ext .js,.jsx,.ts,.tsx; fi

    # Run JavaScript/React Tests (Jest)
    - name: Test JavaScript/React with Jest
      run: |
        if [ -f package.json ]; then npm test; fi
